version: '3.2'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_go_net
    postgres:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: '3'
        ports:
            - '5438:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

networks:
    rabbitmq_go_net:
        driver: bridge
